//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "github_app")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub installation_id: i64,
  #[sea_orm(column_type = "Text")]
  pub github_access_token: String,
  pub github_access_token_expire: TimeDateTimeWithTimeZone,
  pub last_update: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::repository::Entity")]
  Repository,
}

impl Related<super::repository::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Repository.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
