//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "repository")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub github_app: Uuid,
  #[sea_orm(column_type = "Text")]
  pub domain: String,
  pub commit: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub github_name: Option<String>,
  pub trusted: bool,
  pub created_at: TimeDateTimeWithTimeZone,
  pub last_update: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::github_app::Entity",
    from = "Column::GithubApp",
    to = "super::github_app::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  GithubApp,
}

impl Related<super::github_app::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::GithubApp.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
